github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/thisvid-downloader",
  "https://serp.co/products/thisvid-downloader/reviews/",
  "https://extensions.serp.co/thisvid-downloader",
  "https://browserextensions.io/thisvid-downloader"
]
